import {BsThreeDotsVertical} from 'react-icons/bs'
const data = [
    {
      id: '1',
      imgUrl:"https://t4.ftcdn.net/jpg/02/61/52/95/360_F_261529596_YZWJaMnYFSCM0FSCrxs71o6RrZ9MpP4D.jpg",
      student:"student 1",
      class:"class 1",
      subject:"Subect 1",
      timeZone:"Time Zone  1",
      button:<BsThreeDotsVertical/>,
      email: 'Sincere@april.biz',
    },
    {
        id: '2',
        imgUrl:"https://c8.alamy.com/compfr/pyeg09/jeune-femme-prend-des-photos-sur-une-rue-de-la-ville-pyeg09.jpg",
        student:"student 2",
        class:"class 2",
      subject:"Subect 2",
      timeZone:"Time Zone 2",
      button:<BsThreeDotsVertical/>,
      email: 'Shanna@melissa.tv'
    },
    {
        id: '3',
        class:"class 3",
        student:"student 3",
        imgUrl:"https://c8.alamy.com/compfr/pyeg09/jeune-femme-prend-des-photos-sur-une-rue-de-la-ville-pyeg09.jpg",
      subject:"Subect 3",
      timeZone:"Time Zone 3",
      button:<BsThreeDotsVertical/>,
        email: 'Nathan@yesenia.net',
      },
      {
        id: '4',
        imgUrl:"https://c8.alamy.com/comp/D94BM3/excited-and-ready-female-mixed-race-photographer-spots-celebrity-outside-D94BM3.jpg",
        student:"student 4",
        class:"class 4",
      subject:"Subect 4",
      timeZone:"Time Zone 4",
      button:<BsThreeDotsVertical/>,
        email: 'Julianne.OConner@kory.org',
      },
      {
        id: '5',
        imgUrl:"https://img.freepik.com/free-photo/happiness-wellbeing-confidence-concept-cheerful-attractive-african-american-woman-curly-haircut-cross-arms-chest-self-assured-powerful-pose-smiling-determined-wear-yellow-sweater_176420-35063.jpg?size=626&ext=jpg&ga=GA1.1.1413502914.1697241600&semt=sph",
        student:"student 5",
        class:"class 5",
      subject:"Subect 5",
      timeZone:"Time Zone 5",
      button:<BsThreeDotsVertical/>,
        email: 'Lucio_Hettinger@annie.ca',
      },
      {
        id: '6',
        imgUrl:"https://media.istockphoto.com/id/1296158947/photo/portrait-of-creative-trendy-black-african-male-designer-laughing.jpg?s=612x612&w=0&k=20&c=1Ws_LSzWjYvegGxHYQkkgVytdpDcnmK0upJyGOzEPcg=",
        student:"student 6",
        class:"class 6",
      subject:"Subect 6",
      timeZone:"Time Zone 6",
      button:<BsThreeDotsVertical/>,
        email: 'Karley_Dach@jasper.info',
      },
      {
        id: '7',
        imgUrl:"https://www.shutterstock.com/image-photo/handsome-unshaven-young-darkskinned-male-260nw-640011838.jpg",
        student:"student 7",
        class:"class 7",
      subject:"Subect 7",
      timeZone:"Time Zone 7",
      button:<BsThreeDotsVertical/>,
        email: 'Telly.Hoeger@billy.biz',
      },
      {
        id: '8',
        imgUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8CldTqNpzN9ENCGC79zNXg6EfcqEHXTLjQg&usqp=CAU",
        class:"class 8",
        student:"student 8",
      subject:"Subect 8",
      timeZone:"Time Zone 8",
      button:<BsThreeDotsVertical/>,
        email: 'Sherwood@rosamond.me',
      },
      {
        id: '9',
        imgUrl:"https://etimg.etb2bimg.com/photo/97132390.cms",
        student:"student 9",
        class:"class 9",
      subject:"Subect 9",
      timeZone:"Time Zone 9",
      button:<BsThreeDotsVertical/>,
        email: 'Chaim_McDermott@dana.io',
      },
      {
        id: '10',
        imgUrl:"https://polsinelli.gjassets.com/content/uploads/2022/03/OUR-PEOPLE-PRIVTHI-default-people-marquee-image-square-people-marquee-image-1-21529.jpg",
        student:"student 10",
        class:"class 10",
      subject:"Subect 10",
      timeZone:"Time Zone 10",
      button:<BsThreeDotsVertical/>,
        email: 'Rey.Padberg@karina.biz',
      },
    // Add more data as needed
  ];
  export default data;